/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ammSol from "./amm.sol";
export type { ammSol };
import type * as erc20TokensSol from "./erc20tokens.sol";
export type { erc20TokensSol };
